name = "clawsync-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "clawsync"
database_id = "6eac8035-51ee-4aca-b972-e18691bd6162"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "clawsync"
